/* Relational client (service_role) for the client-orders tables.
   Coexists with kv_store.tsx (KV) — same credential pattern as client() there,
   but kv_store.tsx is AUTOGENERATED and must not be touched. */
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

export const db = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// ────────────────────────────────────────────────
// Carrier → tracking URL
// ────────────────────────────────────────────────
export const CARRIER_URLS: Record<string, string> = {
  estafeta: "https://rastreositecoreprod.azurewebsites.net/track?wayBill={track}",
  dhl:      "https://www.dhl.com/mx-es/home/tracking.html?tracking-id={track}",
  fedex:    "https://www.fedex.com/fedextrack/?trknbr={track}",
  ups:      "https://www.ups.com/track?tracknum={track}",
};

export function buildTrackingUrl(carrier?: string | null, track?: string | null): string | null {
  if (!carrier || !track) return null;
  const tmpl = CARRIER_URLS[carrier.trim().toLowerCase()];
  return tmpl ? tmpl.replace("{track}", encodeURIComponent(track)) : null;
}
